# @name create
POST {{host}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "MacBook Pro M3 Max",
  "Category": "Electronics",
  "SubCategory": "Laptops"
}

### Get based on location header
GET {{create.response.headers.Location}}