version: "3.9"

services:
  webapp:
    container_name: one-review-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    container_name: one-review-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=one_review_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
